Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('1AON', 'OUROLANDIA DO NORTE', 'OURILANDIA DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('2NHT', 'HOTEL TRANSAMÉRICA', 'UNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('6ASO', 'SORRISO', 'SORRISO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAA', 'CONCEIÇÃO DO ARAGUAIA', 'CONCEIÇÃO DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAE', 'BAURU/AREALVA', 'AREALVA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAF', 'CAMPO DOS AFONSOS', 'RIO DE JANEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAG', 'ANGRA DOS REIS', 'ANGRA DOS REIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAM', 'AMAPÁ', 'AMAPÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAN', 'BASE AEREA DE ANAPOLIS', 'ANÁPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAQ', 'BARTOLOMEU DE GUSMÃO', 'ARARAQUARA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAR', 'SANTA MARIA', 'ARACAJU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAS', 'MARCELO PIRES HALZHAUSEN', 'ASSIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAT', 'DEPUTADO BENEDITO SANTIAGO', 'ALTA FLORESTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAU', 'ESTADUAL DARIO GUARITA', 'ARAÇATUBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAV', 'USINA PORTO PRIMAVERA', 'TEODORO SAMPAIO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBAX', 'ROMEU ZEMA', 'ARAXÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBE', 'VAL DE CANS', 'BELÉM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBG', 'COMANDANTE GUSTAVO KRAEMER', 'BAGÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBH', 'PAMPULHA - CARLOS DRUMMOND DE ANDRADE', 'BELO HORIZONTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBI', 'BACACHERI', 'CURITIBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBQ', 'MAJOR BRIGADEIRO DO AR DOORGAL GOMES', 'BARBACENA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBR', 'PRESIDENTE JUSCELINO KUBITSCHEK', 'BRASÍLIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBT', 'CHAFEI AMSEI', 'BARRETOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBU', 'BAURU', 'BAURU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBV', 'ATLAS BRASIL CANTANHEDE', 'BOA VISTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBW', 'BARRA DO GARÇAS', 'BARRA DO GARÇAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBBZ', 'UMBERTO MODIANO', 'ARMAÇÃO DE BÚZIOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCA', 'ADALBERTO MENDES DA SILVA', 'CASCAVEL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCB', 'CABO FRIO', 'CABO FRIO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCC', 'CACHIMBO', 'NOVO PROGRESSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCD', 'CARLOS ALBERTO DA COSTA NEVES', 'CAÇADOR'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCF', 'TANCREDO NEVES', 'CONFINS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCG', 'CAMPO GRANDE', 'CAMPO GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCH', 'SERAFIN ENOSS BERTASO', 'CHAPECÓ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCI', 'BRIGADEIRO LYSIAS AUGUSTO RODRIGUES', 'CAROLINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCJ', 'CARAJÁS', 'PARAUAPEBAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCM', 'DIOMÍCIO FREITAS', 'FORQUILHINHA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCN', 'NELSON RODRIGUES GUIMARÃES', 'CALDAS NOVAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCO', 'CANOAS', 'CANOAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCP', 'BARTOLOMEU LISANDRO', 'CAMPOS DOS GOYTACAZES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCR', 'CORUMBÁ', 'CORUMBÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCT', 'AFONSO PENA', 'SÃO JOSÉ DOS PINHAIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCV', 'CARAVELAS', 'CARAVELAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCX', 'REGIONAL HUGO CANTERGIANI', 'CAXIAS DO SUL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCY', 'MARECHAL RONDON', 'VÁRZEA GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBCZ', 'CRUZEIRO DO SUL', 'CRUZEIRO DO SUL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBDB', 'BONITO', 'BONITO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBDN', 'PRESIDENTE PRUDENTE', 'PRESIDENTE PRUDENTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBDO', 'AEROPORTO MUNCIPAL DE DOURADOS', 'DOURADOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBEG', 'EDUARDO GOMES', 'MANAUS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBEK', 'JACAREACANGA', 'JACAREACANGA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBFC', 'TENENTE LUND PRESETTO', 'FRANCA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBFI', 'CATARATAS', 'FOZ DO IGUAÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBFL', 'HERCÍLIO LUZ', 'FLORIANÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBFN', 'FERNANDO DE NORONHA', 'FERNANDO DE NORONHA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBFZ', 'PINTO MARTINS', 'FORTALEZA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGL', 'AEROPORTO INTERNACIONAL DO RIO DE JANEIRO/GALEÃO – ANTONIO CARLOS JOBIM', 'RIO DE JANEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGM', 'GUAJARÁ-MIRIM', 'GUAJARÁ-MIRIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGO', 'SANTA GENOVEVA', 'GOIÂNIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGP', 'EMBRAER-UNIDADE GAVIAO PEIXOTO', 'GAVIÃO PEIXOTO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGR', 'GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO', 'GUARULHOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGS', 'PONTA GROSSA', 'PONTA GROSSA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGU', 'TANCREDO THOMAS DE FARIA', 'GUARAPUAVA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBGV', 'CORONEL ALTINO MACHADO', 'GOVERNADOR VALADARES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBHT', 'ALTAMIRA', 'ALTAMIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIC', 'ITACOATIARA', 'ITACOATIARA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIH', 'ITAITUBA', 'ITAITUBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIL', 'BAHIA - JORGE AMADO', 'ILHÉUS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIP', 'USIMINAS', 'SANTANA DO PARAÍSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIT', 'Aeroporto de Itumbiara - Francisco Vilela do Amaral', 'Itumbiara'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBIZ', 'PREFEITO RENATO MOREIRA', 'IMPERATRIZ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJA', 'REGIONAL SUL', 'JAGUARUNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJC', 'JÚLIO CESAR', 'BELÉM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJD', 'AEROPORTO DE JUNDIAÍ', 'JUNDIAÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJF', 'FRANCISCO DE ASSIS', 'JUIZ DE FORA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJI', 'JI-PARANÁ', 'JI-PARANÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJP', 'PRESIDENTE CASTRO PINTO', 'BAYEUX'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJR', 'JACAREPAGUÁ/RJ - ROBERTO MARINHO', 'RIO DE JANEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJU', 'ORLANDO BEZERRA DE MENEZES', 'JUAZEIRO DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBJV', 'LAURO CARNEIRO DE LOYOLA', 'JOINVILLE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBKG', 'PRESIDENTE JOÃO SUASSUNA', 'CAMPINA GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBKP', 'VIRACOPOS', 'CAMPINAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBLE', 'HORÁCIO DE MATTOS', 'LENÇÓIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBLJ', 'CORREIA PINTO', 'LAGES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBLN', 'GOVERNADOR LUCAS NOGUEIRA GARCEZ', 'LINS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBLO', 'GOVERNADOR JOSÉ RICHA', 'LONDRINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBLP', 'BOM JESUS DA LAPA', 'BOM JESUS DA LAPA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMA', 'MARABÁ', 'MARABÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMC', 'MINAÇU', 'MINAÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMD', 'MONTE DOURADO', 'ALMEIRIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBME', 'MACAÉ', 'MACAÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMG', 'REGIONAL DE MARINGÁ - SÍLVIO NAME JÚNIOR', 'MARINGÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMH', 'MARINGÁ', 'MARINGÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMK', 'MÁRIO RIBEIRO', 'MONTES CLAROS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBML', 'FRANK MILOYE MILENKOVICH', 'MARÍLIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMN', 'PONTA PELADA', 'MANAUS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMO', 'ZUMBI DOS PALMARES', 'RIO LARGO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMQ', 'MACAPÁ', 'MACAPÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMS', 'DIX-SEPT ROSADO', 'MOSSORÓ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMT', 'CAMPO DE MARTE', 'SÃO PAULO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBMY', 'MANICORÉ', 'MANICORÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBNF', 'MINISTRO VICTOR KONDER', 'NAVEGANTES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBNM', 'SANTO ÂNGELO', 'SANTO ÂNGELO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBNT', 'AUGUSTO SEVERO', 'PARNAMIRIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBOI', 'OIAPOQUE', 'OIAPOQUE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPA', 'SALGADO FILHO', 'PORTO ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPB', 'PREFEITO DOUTOR JOÃO SILVA FILHO', 'PARNAÍBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPC', 'EMBAIXADOR WALTHER MOREIRA SALLES', 'POÇOS DE CALDAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPF', 'LAURO KURTZ', 'PASSO FUNDO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPJ', 'BRIGADEIRO LYSIAS RODRIGUES', 'PALMAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPK', 'PELOTAS', 'PELOTAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPL', 'SENADOR NILO COELHO', 'PETROLINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPM', 'PALMAS', 'PALMAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPN', 'PORTO NACIONAL', 'PORTO NACIONAL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPP', 'PONTA PORÃ', 'PONTA PORÃ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPS', 'PORTO SEGURO', 'PORTO SEGURO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBPV', 'GOVERNADOR JORGE TEIXEIRA DE OLIVEIRA', 'PORTO VELHO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBQV', 'VITÓRIA DA CONQUISTA', 'VITÓRIA DA CONQUISTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRB', 'PLÁCIDO DE CASTRO', 'SENA MADUREIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRD', 'RONDONÓPOLIS', 'RONDONÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRF', 'GUARARAPES - GILBERTO FREYRE', 'RECIFE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRG', 'RIO GRANDE', 'RIO GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRJ', 'SANTOS DUMONT', 'RIO DE JANEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBRP', 'LEITE LOPES', 'RIBEIRÃO PRETO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSC', 'BARTOLOMEU DE GUSMAO', 'RIO DE JANEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSG', 'SÃO GONÇALO DO AMARANTE', 'SÃO GONÇALO DO AMARANTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSJ', 'PROFESSOR URBANO ERNESTO STUMPF', 'SÃO JOSÉ DOS CAMPOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSL', 'MARECHAL CUNHA MACHADO', 'SÃO LUÍS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSM', 'SANTA MARIA', 'SANTA MARIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSN', 'MAESTRO WILSON FONSECA', 'SANTARÉM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSP', 'CONGONHAS', 'SÃO PAULO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSR', 'PROFESSOR ERIBERTO MANOEL REINO', 'SÃO JOSÉ DO RIO PRETO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBST', 'BASE AEREA', 'SANTOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBSV', 'DEPUTADO LUÍS EDUARDO MAGALHÃES', 'SALVADOR'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTB', 'TROMBETAS', 'ORIXIMINÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTC', 'HOTEL TRANSAMÉRICA', 'UNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTD', 'LUÍS DAL CANALLE FILHO', 'TOLEDO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTE', 'SENADOR PETRÔNIO PORTELLA', 'TERESINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTF', 'TEFÉ', 'TEFÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTG', 'AEROPORTO REGIONAL PLÍNIO ALARCON', 'TRÊS LAGOAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTK', 'TARAUACÁ', 'TARAUACÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTL', 'TELÊMACO BORBA', 'TELÊMACO BORBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTR', 'TORRES', 'TORRES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTS', 'TIRIOS', 'ÓBIDOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTT', 'TABATINGA', 'TABATINGA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTU', 'TUCURUÍ', 'TUCURUÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBTV', 'TERRAVISTA', 'PORTO SEGURO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUA', 'SÃO GABRIEL DA CACHOEIRA', 'SÃO GABRIEL DA CACHOEIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUF', 'PAULO AFONSO', 'PAULO AFONSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUG', 'RUBEM BERTA', 'URUGUAIANA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUL', 'TENENTE-CORONEL AVIADOR CÉSAR BOMBONATO', 'UBERLÂNDIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUR', 'MÁRIO DE ALMEIDA FRANCO', 'UBERABA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBUY', 'URUCU', 'COARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBVG', 'MAJOR BRIGADEIRO TROMPOWSKY', 'VARGINHA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBVH', 'BRIGADEIRO CAMARÃO', 'VILHENA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBVT', 'EURICO DE AGUIAR SALLES', 'VITÓRIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBYA', 'IAUARETÊ', 'SÃO GABRIEL DA CACHOEIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBYS', 'CAMPO FONTENELLE/ACADEMIA DA FORÇA AÉREA', 'PIRASSUNUNGA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SBZM', 'REGIONAL DA ZONA DA MATA', 'GOIANÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDAA', 'ARARAS', 'ARARAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDAG', 'ANGRA DOS REIS', 'ANGRA DOS REIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDAM', 'AMARAIS', 'CAMPINAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDBB', 'BEBEDOURO', 'BEBEDOURO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDBK', 'TANCREDO DE ALMEIDA NEVES', 'BOTUCATU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDCG', 'SENADORA EUNICE MICHILES', 'SÃO PAULO DE OLIVENÇA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDCO', 'SOROCABA', 'SOROCABA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDFR', 'CABO FRIO', 'CABO FRIO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDLK', 'CACULÉ', 'CACULÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDLU', 'FAZENDA SANTA LUZIA', 'BARRA BONITA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDMC', 'MARICÁ', 'MARICÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDOU', 'OURINHOS', 'OURINHOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDOV', 'MOZARLÂNDIA', 'MOZARLÂNDIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDOW', 'OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDPA', 'FAZ. PORTO BELO', 'MANGARATIBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDRS', 'RESENDE', 'RESENDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDSC', 'MÁRIO PEREIRA LOPES', 'SÃO CARLOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDTK', 'PARATI', 'PARATI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDUB', 'GASTÃO MADEIRA', 'UBATUBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDUN', 'ITAPERUNA', 'ITAPERUNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDVE', 'VERA CRUZ', 'VERA CRUZ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDVG', 'DOMINGOS PIGNATARI', 'VOTUPORANGA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SDZY', 'AEROPORTO REGIONAL DE ZONA DA MATA', 'JUIZ DE FORA/UBÁ/CATAGUASES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIBU', 'CATOLÉ DO ROCHA', 'CATOLÉ DO ROCHA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIFV', 'ARACRUZ', 'ARACRUZ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIGP', 'GAVIAO PEIXOTO', 'GAVIÃO PEIXOTO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIKC', 'COLIDER', 'COLÍDER'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SILC', 'LUCAS DO RIO VERDE', 'LUCAS DO RIO VERDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SILJ', 'LARANJAL DO JARI', 'LARANJAL DO JARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIMK', 'TENENTE LUND PRESETTO', 'FRANCA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIQE', 'BOTELHO', 'BRASÍLIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIRI', 'BARRA GRANDE', 'Maraú'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SISO', 'FAZENDA SANTO AMBROSIO', 'CHAVES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIXE', 'AEROCLUBE DE ELDORADO DO SUL', 'ELDORADO DO SUL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SIZX', 'JUARA SUL', 'JUARA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJCW', 'JATAPU', 'URUCARÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJDB', 'BONITO', 'BONITO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJGU', 'AERÓDROMO ARAGUATINS', 'ARAGUATINS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJHG', 'CONFRESA', 'CONFRESA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJKB', 'COTRIGUACU', 'COTRIGUAÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJLM', 'LEÃO DE OURO', 'PACAIMA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJLU', 'MISSAO CATRIMANI', 'CARACARAÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJNP', 'NOVO PROGRESSO', 'NOVO PROGRESSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJQK', 'BARRA DO VENTO', 'BOA VISTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJQP', 'ESTÂNCIA REBOG', 'COCALINHO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJRG', 'RIO GRANDE', 'RIO GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJTC', 'MOUSSA NAKHL TOBIAS', 'AREALVA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJTS', 'TERRA SANTA', 'TERRA SANTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJUQ', 'FAZENDA VISTA ALEGRE', 'TRÊS LAGOAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJUR', 'TERRAVISTA', 'PORTO SEGURO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SJVO', 'ARAGARÇAS', 'ARAGARÇAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNAB', 'ARARIPINA', 'ARARIPINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNAH', 'ADUSTINA', 'ADUSTINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNAP', 'JANAÚBA', 'JANAÚBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNAT', 'ARACATI', 'ARACATI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNAV', 'AGROVALE', 'JUAZEIRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBA', 'CHAFEI AMSEI', 'BARRETOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBI', 'BACABAL', 'BACABAL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBR', 'BARREIRAS', 'BARREIRAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBS', 'BALSAS', 'BALSAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBU', 'BRUMADO', 'BRUMADO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBV', 'CAMPO DE BOI', 'IPIXUNA DO PARÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBW', 'BAIÃO', 'BAIÃO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNBX', 'BARRA', 'BARRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNCB', 'CAMPO DE BOI', 'IPIXUNA DO PARÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNCI', 'CIBRASA', 'CAPANEMA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDB', 'RURÓPOLIS', 'RURÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDC', 'REDENÇÃO', 'REDENÇÃO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDH', 'ABA', 'BARREIRAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDM', 'CHAPADA DIAMANTINA', 'LENÇÓIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDR', 'DOMINGOS REGO', 'TIMON'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDT', 'DIAMANTINA', 'DIAMANTINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNDV', 'BRIGADEIRO CABRAL', 'DIVINÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNEB', 'PARAGOMINAS', 'PARAGOMINAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNFE', 'COMANDANTE PASCHOAL PATROCÍNIO FILHO', 'ALFENAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNFX', 'SÃO FÉLIX DO XINGU', 'SÃO FÉLIX DO XINGU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNGI', 'GUANAMBI', 'GUANAMBI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNGV', 'GOVERNADOR VALADARES', 'GOVERNADOR VALADARES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNHS', 'SANTA MAGALHÃES', 'SERRA TALHADA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNIC', 'IRECÊ', 'IRECÊ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNIG', 'IGUATU', 'IGUATU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNIU', 'IPIAÚ', 'IPIAÚ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNJB', 'JACOBINA', 'JACOBINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNJD', 'JOÃO DURVAL CARNEIRO', 'FEIRA DE SANTANA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNJK', 'JEQUIÉ', 'JEQUIÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNJR', 'SÃO JOÃO DEL REI', 'SÃO JOÃO DEL REI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNKE', 'SANTANA DO ARAGUAIA', 'SANTANA DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNKI', 'CACHOEIRO DE ITAPEMIRIM', 'CACHOEIRO DE ITAPEMIRIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNKK', 'CAICÓ', 'CAICÓ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNLA', 'AGROPECUARIA UMUARAMA', 'PARAUAPEBAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMA', 'MONTE ALEGRE', 'MONTE ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMD', 'MUNDICO COELHO', 'ITAITUBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMH', 'AEROPORTO DE PIRENÓPOLIS', 'PIRENÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMJ', 'MARACÁS', 'MARACÁS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMK', 'MOCAMBINHO', 'JAÍBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNML', 'MANDUCA LEAO', 'RIO LARGO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMU', 'MUCURI', 'MUCURI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMX', 'SÃO MATEUS', 'SÃO MATEUS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNMZ', 'PORTO DE MOZ', 'PORTO DE MOZ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNNC', 'RIO CAPIM', 'IPIXUNA DO PARÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNNG', 'PROGRESSO', 'NOVO PROGRESSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNOB', 'VIRGÍLIO TÁVORA', 'SOBRAL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNOX', 'ORIXIMINÁ', 'ORIXIMINÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPC', 'PICOS', 'PICOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPD', 'PATOS DE MINAS', 'PATOS DE MINAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPG', 'PORTO GRANDE', 'PORTO GRANDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPJ', 'PATROCÍNIO', 'PATROCÍNIO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPP', 'MORRO DE SÃO PAULO', 'MORRO DE SÃO PAULO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPV', 'PORTO DE VILA DO CONDE', 'BARCARENA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNPY', 'SÃO SEBASTIÃO DO PARAÍSO', 'SÃO SEBASTIÃO DO PARAÍSO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNQD', 'SOUSA', 'SOUSA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNQG', 'CANGAPARA', 'FLORIANO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNQW', 'CURURU', 'JACAREACANGA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNQY', 'CARIRI', 'JUAZEIRO DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNRB', 'ROSA BRANCA', 'ITAITUBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNRU', 'OSCAR LARANJEIRAS', 'CARUARU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNSH', 'SAO JOSE', 'SANTARÉM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNSM', 'SALINÓPOLIS', 'SALINÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNSW', 'SOURE', 'SOURE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNTF', 'TEIXEIRA DE FREITAS', 'TEIXEIRA DE FREITAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNTI', 'ÓBIDOS', 'ÓBIDOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNTO', 'JUSCELINO KUBITSCHECK', 'TEÓFILO OTONI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNTP', 'AGROPALMA', 'TAILÂNDIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNTS', 'PEREGRINO FILHO', 'PATOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNUB', 'UBÁ', 'UBÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNUC', 'AÇU', 'AÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNUI', 'ARAÇUAÍ', 'ARAÇUAÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNUO', 'ULIANÓPOLIS', 'ULIANÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNVB', 'VALENÇA', 'VALENÇA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNVR', 'AEROCLUBE DA BAHIA', 'VERA CRUZ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNVS', 'BREVES', 'BREVES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNVV', 'VALENTE', 'VALENTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNWR', 'WILMA REBELO', 'SENADOR JOSÉ PORFÍRIO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNXL', 'PRIMAVERA', 'QUERÊNCIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNXW', 'CHAVES', 'CHAVES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNYA', 'ALMEIRIM', 'ALMEIRIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNYB', 'TITO TEIXEIRA', 'ITUIUTABA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNYV', 'FAZENDA SOCOCO', 'MOJU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SNZA', 'POUSO ALEGRE', 'POUSO ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSAC', 'FAZENDA NOVA JERUSALÉM', 'SORRISO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSBB', 'ESTRELA DALVA', 'BODOQUENA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSBG', 'AEROCLUBE', 'BENTO GONÇALVES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSBN', 'BELÉM NOVO', 'PORTO ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSCC', 'CACADOR', 'CAÇADOR'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSCK', 'OLAVO CECCO RIGON', 'CONCÓRDIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSCN', 'CANELA', 'CANELA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSDO', 'MUNICIPAL FRANCISCO DE MATOS PEREIRA', 'DOURADOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSER', 'ERECHIM', 'ERECHIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSFB', 'AEROPORTO PAULO ABDALA', 'FRANCISCO BELTRÃO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSHZ', 'WALTER BÜNDCHEN', 'HORIZONTINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSIJ', 'IJUÍ', 'IJUÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSJA', 'SANTA TEREZINHA', 'JOAÇABA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSKM', 'GERALDO GUIAS DE AQUINO', 'CAMPO MOURÃO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSKW', 'CACOAL', 'CACOAL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSLS', 'SALTO SANTIAGO', 'LARANJEIRAS DO SUL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSLT', 'GAUDÊNCIO MACHADO RAMOS', 'ALEGRETE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSNC', 'FAZENDA CORRENTÃO', 'APORÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSND', 'SANTA MARIA', 'SÃO FÉLIX DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSNH', 'NOVO HAMBURGO', 'NOVO HAMBURGO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSNM', 'GUARANTÃ', 'GUARANTÃ DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSOE', 'HÉLIO WASUM', 'SÃO MIGUEL DO OESTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSPB', 'JUVENAL LOUREIRO CARDOSO', 'PATO BRANCO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSPG', 'SANTOS DUMONT', 'PARANAGUÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSPK', 'PORECATU', 'PORECATU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSSC', 'SANTA CRUZ DO SUL', 'SANTA CRUZ DO SUL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSTD', 'TOLEDO', 'TOLEDO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSTL', 'AEROPORTO REGIONAL PLÍNIO ALARCON', 'TRÊS LAGOAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSUM', 'ORLANDO DE CARVALHO', 'UMUARAMA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSUW', 'GUARAPUAVA', 'GUARAPUAVA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSVI', 'ÂNGELO PONZONI', 'VIDEIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SSZR', 'SANTA ROSA', 'SANTA ROSA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWAE', 'UAICAS', 'ALTO ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBC', 'BARCELOS', 'BARCELOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBI', 'BARREIRINHA', 'BARREIRINHA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBR', 'BORBA', 'BORBA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBU', 'FAZENDA FARTURA BAIXAO NOVO', 'PEIXOTO DE AZEVEDO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBV', 'AUARIS', 'AMAJARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWBZ', 'JPO SORRISO', 'SORRISO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWCA', 'CARAUARI', 'CARAUARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWCB', 'CAMPOS BELOS', 'CAMPOS BELOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWCI', 'COLNIZA', 'ARIPUANÃ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWCP', 'CAMPO NOVO DOS PARECIS', 'CAMPO NOVO DO PARECIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWCQ', 'COSTA MARQUES', 'COSTA MARQUES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWDB', 'AERÓDROMO FAZENDA ELDORADO', 'BARRA DO GARÇAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWDE', 'FAZENDA PIRATININGA', 'SÃO MIGUEL DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWDM', 'DIAMANTINO', 'DIAMANTINO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWEE', 'ESTIRÃO DO EQUADOR', 'ATALAIA DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWEI', 'EIRUNEPÉ', 'EIRUNEPÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWEK', 'CANARANA', 'CANARANA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWEU', 'CARACARAI', 'CARACARAÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWFJ', 'FEIJÓ', 'FEIJÓ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWFN', 'FLORES', 'MANAUS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWFX', 'SÃO FÉLIX DO ARAGUAIA', 'SÃO FÉLIX DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWGI', 'GURUPI', 'GURUPI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWGN', 'ARAGUAÍNA', 'ARAGUAÍNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWGP', 'PALMEIRAS DE GOIÁS', 'PALMEIRAS DE GOIÁS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWHG', 'AEROPORTO DE SANTA HELENA DO GOIÁS', 'SANTA HELENA DO GOIÁS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWHP', 'FAZENDA OLHO DAGUA', 'ÁGUA BOA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWHT', 'FRANCISCO CORREA DA CRUZ', 'HUMAITÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWII', 'IPIRANGA', 'SANTO ANTÔNIO DO IÇÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWIQ', 'MINAÇU', 'MINAÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJH', 'JUARA', 'JUARA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJI', 'JI-PARANÁ', 'JI-PARANÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJN', 'JUÍNA', 'JUÍNA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJP', 'BITTENCOURT', 'JAPURÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJQ', 'FAZENDA COLIBRI', 'SELVÍRIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJU', 'JURUENA', 'JURUENA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWJW', 'JATAÍ', 'JATAÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWKC', 'CÁCERES', 'CÁCERES'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWKK', 'CACOAL', 'CACOAL'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWKN', 'CALDAS NOVAS', 'CALDAS NOVAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWKO', 'COARI', 'COARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWLB', 'LÁBREA', 'LÁBREA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWLC', 'GENERAL LEITE DE CASTRO', 'RIO VERDE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWLV', 'ESTANCIA SANTO ANTONIO', 'SANTO ANTÔNIO DO LEVERGER'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWMP', 'MATUPA', 'GUARANTÃ DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWMW', 'MAUÉS', 'MAUÉS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNA', 'NOVO ARIPUANÃ', 'NOVO ARIPUANÃ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNH', 'ARUANÃ', 'ARUANÃ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNK', 'NOVO CAMPO', 'BOCA DO ACRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNO', 'NOVA OLINDA DO NORTE', 'NOVA OLINDA DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNQ', 'NIQUELÂNDIA', 'NIQUELÂNDIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWNS', 'ANÁPOLIS', 'ANÁPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWOB', 'FONTE BOA', 'FONTE BOA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWOW', 'MOURA', 'BARCELOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPC', 'PARI-CACHOEIRA', 'SÃO GABRIEL DA CACHOEIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPD', 'POUSO DAAGUIA', 'BONFIM'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPF', 'PITINGA', 'PRESIDENTE FIGUEIREDO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPI', 'JÚLIO BÉLEM', 'PARINTINS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPJ', 'PALMAS', 'PALMAS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWPQ', 'PIRAGUASSU', 'PORTO ALEGRE DO NORTE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWQR', 'ESTÂNCIA MONTENEGRO', 'BOA VISTA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWRD', 'RONDONÓPOLIS', 'RONDONÓPOLIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWRP', 'ARIPUANA', 'ARIPUANÃ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWSI', 'PRESIDENTE JOÃO BATISTA FIGUEIREDO', 'SINOP'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWSQ', 'SÃO JOAQUIM', 'SÃO GABRIEL DA CACHOEIRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWTP', 'TAPURUQUARA', 'SANTA ISABEL DO RIO NEGRO'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWTS', 'TANGARÁ DA SERRA', 'TANGARÁ DA SERRA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWTU', 'FAZENDA TUCUNARE', 'CAMPO NOVO DO PARECIS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWUA', 'SÃO MIGUEL DO ARAGUAIA', 'SÃO MIGUEL DO ARAGUAIA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWUQ', 'SURUCUCU OU SURUCURU', 'ALTO ALEGRE'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWUY', 'URUCU', 'COARI'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWVC', 'VILA RICA', 'VILA RICA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWVR', 'ESTANCIA ROSALIA', 'SINOP'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWWA', 'PORANGATU', 'PORANGATU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWWD', 'BARCELOS', 'BARCELOS'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWWU', 'URUAÇU', 'URUAÇU'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWXM', 'REGIONAL ORLANDO VILLAS BOAS', 'MATUPÁ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWXV', 'XAVANTINA', 'NOVA XAVANTINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWYK', 'FAZENDA ILHA CAMARGO', 'POCONÉ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWYN', 'PRAINHA', 'APUÍ'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWYY', 'AEROPORTO FAZENDA NOVA VIENA', 'NOVA XAVANTINA'); 
Insert Into Aeroporto (Estado, Periodo, NumCasos) Values ('SWZM', 'USINA SÃO SIMÃO', 'USINA SÃO SIMÃO'); 
