Insert Into Cidade (Nome, Estado) Values ('PA', 'OURILANDIA DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('BA', 'UNA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'SORRISO');
Insert Into Cidade (Nome, Estado) Values ('PA', 'CONCEIÇÃO DO ARAGUAIA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'AREALVA');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'RIO DE JANEIRO');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'ANGRA DOS REIS');
Insert Into Cidade (Nome, Estado) Values ('AP', 'AMAPÁ');
Insert Into Cidade (Nome, Estado) Values ('GO', 'ANÁPOLIS');
Insert Into Cidade (Nome, Estado) Values ('SP', 'ARARAQUARA');
Insert Into Cidade (Nome, Estado) Values ('SE', 'ARACAJU');
Insert Into Cidade (Nome, Estado) Values ('SP', 'ASSIS');
Insert Into Cidade (Nome, Estado) Values ('MT', 'ALTA FLORESTA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'ARAÇATUBA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'TEODORO SAMPAIO');
Insert Into Cidade (Nome, Estado) Values ('MG', 'ARAXÁ');
Insert Into Cidade (Nome, Estado) Values ('PA', 'BELÉM');
Insert Into Cidade (Nome, Estado) Values ('RS', 'BAGÉ');
Insert Into Cidade (Nome, Estado) Values ('MG', 'BELO HORIZONTE');
Insert Into Cidade (Nome, Estado) Values ('PR', 'CURITIBA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'BARBACENA');
Insert Into Cidade (Nome, Estado) Values ('DF', 'BRASÍLIA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'BARRETOS');
Insert Into Cidade (Nome, Estado) Values ('SP', 'BAURU');
Insert Into Cidade (Nome, Estado) Values ('RR', 'BOA VISTA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'BARRA DO GARÇAS');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'ARMAÇÃO DE BÚZIOS');
Insert Into Cidade (Nome, Estado) Values ('PR', 'CASCAVEL');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'CABO FRIO');
Insert Into Cidade (Nome, Estado) Values ('PA', 'NOVO PROGRESSO');
Insert Into Cidade (Nome, Estado) Values ('SC', 'CAÇADOR');
Insert Into Cidade (Nome, Estado) Values ('MG', 'CONFINS');
Insert Into Cidade (Nome, Estado) Values ('MS', 'CAMPO GRANDE');
Insert Into Cidade (Nome, Estado) Values ('SC', 'CHAPECÓ');
Insert Into Cidade (Nome, Estado) Values ('MA', 'CAROLINA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'PARAUAPEBAS');
Insert Into Cidade (Nome, Estado) Values ('SC', 'FORQUILHINHA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'CALDAS NOVAS');
Insert Into Cidade (Nome, Estado) Values ('RS', 'CANOAS');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'CAMPOS DOS GOYTACAZES');
Insert Into Cidade (Nome, Estado) Values ('MS', 'CORUMBÁ');
Insert Into Cidade (Nome, Estado) Values ('PR', 'SÃO JOSÉ DOS PINHAIS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'CARAVELAS');
Insert Into Cidade (Nome, Estado) Values ('RS', 'CAXIAS DO SUL');
Insert Into Cidade (Nome, Estado) Values ('MT', 'VÁRZEA GRANDE');
Insert Into Cidade (Nome, Estado) Values ('AC', 'CRUZEIRO DO SUL');
Insert Into Cidade (Nome, Estado) Values ('MS', 'BONITO');
Insert Into Cidade (Nome, Estado) Values ('SP', 'PRESIDENTE PRUDENTE');
Insert Into Cidade (Nome, Estado) Values ('MS', 'DOURADOS');
Insert Into Cidade (Nome, Estado) Values ('AM', 'MANAUS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'JACAREACANGA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'FRANCA');
Insert Into Cidade (Nome, Estado) Values ('PR', 'FOZ DO IGUAÇU');
Insert Into Cidade (Nome, Estado) Values ('SC', 'FLORIANÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('PE', 'FERNANDO DE NORONHA');
Insert Into Cidade (Nome, Estado) Values ('CE', 'FORTALEZA');
Insert Into Cidade (Nome, Estado) Values ('RO', 'GUAJARÁ-MIRIM');
Insert Into Cidade (Nome, Estado) Values ('GO', 'GOIÂNIA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'GAVIÃO PEIXOTO');
Insert Into Cidade (Nome, Estado) Values ('SP', 'GUARULHOS');
Insert Into Cidade (Nome, Estado) Values ('PR', 'PONTA GROSSA');
Insert Into Cidade (Nome, Estado) Values ('PR', 'GUARAPUAVA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'GOVERNADOR VALADARES');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ALTAMIRA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'ITACOATIARA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ITAITUBA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'ILHÉUS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'SANTANA DO PARAÍSO');
Insert Into Cidade (Nome, Estado) Values ('GO', 'Itumbiara');
Insert Into Cidade (Nome, Estado) Values ('MA', 'IMPERATRIZ');
Insert Into Cidade (Nome, Estado) Values ('SC', 'JAGUARUNA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'JUNDIAÍ');
Insert Into Cidade (Nome, Estado) Values ('MG', 'JUIZ DE FORA');
Insert Into Cidade (Nome, Estado) Values ('RO', 'JI-PARANÁ');
Insert Into Cidade (Nome, Estado) Values ('PB', 'BAYEUX');
Insert Into Cidade (Nome, Estado) Values ('CE', 'JUAZEIRO DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('SC', 'JOINVILLE');
Insert Into Cidade (Nome, Estado) Values ('PB', 'CAMPINA GRANDE');
Insert Into Cidade (Nome, Estado) Values ('SP', 'CAMPINAS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'LENÇÓIS');
Insert Into Cidade (Nome, Estado) Values ('SC', 'LAGES');
Insert Into Cidade (Nome, Estado) Values ('SP', 'LINS');
Insert Into Cidade (Nome, Estado) Values ('PR', 'LONDRINA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'BOM JESUS DA LAPA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'MARABÁ');
Insert Into Cidade (Nome, Estado) Values ('GO', 'MINAÇU');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ALMEIRIM');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'MACAÉ');
Insert Into Cidade (Nome, Estado) Values ('PR', 'MARINGÁ');
Insert Into Cidade (Nome, Estado) Values ('MG', 'MONTES CLAROS');
Insert Into Cidade (Nome, Estado) Values ('SP', 'MARÍLIA');
Insert Into Cidade (Nome, Estado) Values ('AL', 'RIO LARGO');
Insert Into Cidade (Nome, Estado) Values ('AP', 'MACAPÁ');
Insert Into Cidade (Nome, Estado) Values ('RN', 'MOSSORÓ');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SÃO PAULO');
Insert Into Cidade (Nome, Estado) Values ('AM', 'MANICORÉ');
Insert Into Cidade (Nome, Estado) Values ('SC', 'NAVEGANTES');
Insert Into Cidade (Nome, Estado) Values ('RS', 'SANTO ÂNGELO');
Insert Into Cidade (Nome, Estado) Values ('RN', 'PARNAMIRIM');
Insert Into Cidade (Nome, Estado) Values ('AP', 'OIAPOQUE');
Insert Into Cidade (Nome, Estado) Values ('RS', 'PORTO ALEGRE');
Insert Into Cidade (Nome, Estado) Values ('PI', 'PARNAÍBA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'POÇOS DE CALDAS');
Insert Into Cidade (Nome, Estado) Values ('RS', 'PASSO FUNDO');
Insert Into Cidade (Nome, Estado) Values ('TO', 'PALMAS');
Insert Into Cidade (Nome, Estado) Values ('RS', 'PELOTAS');
Insert Into Cidade (Nome, Estado) Values ('PE', 'PETROLINA');
Insert Into Cidade (Nome, Estado) Values ('TO', 'PORTO NACIONAL');
Insert Into Cidade (Nome, Estado) Values ('MS', 'PONTA PORÃ');
Insert Into Cidade (Nome, Estado) Values ('BA', 'PORTO SEGURO');
Insert Into Cidade (Nome, Estado) Values ('RO', 'PORTO VELHO');
Insert Into Cidade (Nome, Estado) Values ('BA', 'VITÓRIA DA CONQUISTA');
Insert Into Cidade (Nome, Estado) Values ('AC', 'SENA MADUREIRA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'RONDONÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('PE', 'RECIFE');
Insert Into Cidade (Nome, Estado) Values ('RS', 'RIO GRANDE');
Insert Into Cidade (Nome, Estado) Values ('SP', 'RIBEIRÃO PRETO');
Insert Into Cidade (Nome, Estado) Values ('RN', 'SÃO GONÇALO DO AMARANTE');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SÃO JOSÉ DOS CAMPOS');
Insert Into Cidade (Nome, Estado) Values ('MA', 'SÃO LUÍS');
Insert Into Cidade (Nome, Estado) Values ('RS', 'SANTA MARIA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SANTARÉM');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SÃO JOSÉ DO RIO PRETO');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SANTOS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'SALVADOR');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ORIXIMINÁ');
Insert Into Cidade (Nome, Estado) Values ('BA', 'UNA');
Insert Into Cidade (Nome, Estado) Values ('PR', 'TOLEDO');
Insert Into Cidade (Nome, Estado) Values ('PI', 'TERESINA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'TEFÉ');
Insert Into Cidade (Nome, Estado) Values ('MS', 'TRÊS LAGOAS');
Insert Into Cidade (Nome, Estado) Values ('AC', 'TARAUACÁ');
Insert Into Cidade (Nome, Estado) Values ('PR', 'TELÊMACO BORBA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'TORRES');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ÓBIDOS');
Insert Into Cidade (Nome, Estado) Values ('AM', 'TABATINGA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'TUCURUÍ');
Insert Into Cidade (Nome, Estado) Values ('AM', 'SÃO GABRIEL DA CACHOEIRA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'PAULO AFONSO');
Insert Into Cidade (Nome, Estado) Values ('RS', 'URUGUAIANA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'UBERLÂNDIA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'UBERABA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'COARI');
Insert Into Cidade (Nome, Estado) Values ('MG', 'VARGINHA');
Insert Into Cidade (Nome, Estado) Values ('RO', 'VILHENA');
Insert Into Cidade (Nome, Estado) Values ('ES', 'VITÓRIA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'PIRASSUNUNGA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'GOIANÁ');
Insert Into Cidade (Nome, Estado) Values ('SP', 'ARARAS');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'ANGRA DOS REIS');
Insert Into Cidade (Nome, Estado) Values ('SP', 'BEBEDOURO');
Insert Into Cidade (Nome, Estado) Values ('SP', 'BOTUCATU');
Insert Into Cidade (Nome, Estado) Values ('AM', 'SÃO PAULO DE OLIVENÇA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SOROCABA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'CACULÉ');
Insert Into Cidade (Nome, Estado) Values ('SP', 'BARRA BONITA');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'MARICÁ');
Insert Into Cidade (Nome, Estado) Values ('SP', 'OURINHOS');
Insert Into Cidade (Nome, Estado) Values ('GO', 'MOZARLÂNDIA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'OURILÂNDIA DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'MANGARATIBA');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'RESENDE');
Insert Into Cidade (Nome, Estado) Values ('SP', 'SÃO CARLOS');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'PARATI');
Insert Into Cidade (Nome, Estado) Values ('SP', 'UBATUBA');
Insert Into Cidade (Nome, Estado) Values ('RJ', 'ITAPERUNA');
Insert Into Cidade (Nome, Estado) Values ('SP', 'VERA CRUZ');
Insert Into Cidade (Nome, Estado) Values ('SP', 'VOTUPORANGA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'JUIZ DE FORA/UBÁ/CATAGUASES');
Insert Into Cidade (Nome, Estado) Values ('PB', 'CATOLÉ DO ROCHA');
Insert Into Cidade (Nome, Estado) Values ('ES', 'ARACRUZ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'COLÍDER');
Insert Into Cidade (Nome, Estado) Values ('MT', 'LUCAS DO RIO VERDE');
Insert Into Cidade (Nome, Estado) Values ('AP', 'LARANJAL DO JARI');
Insert Into Cidade (Nome, Estado) Values ('BA', 'Maraú');
Insert Into Cidade (Nome, Estado) Values ('PA', 'CHAVES');
Insert Into Cidade (Nome, Estado) Values ('RS', 'ELDORADO DO SUL');
Insert Into Cidade (Nome, Estado) Values ('MT', 'JUARA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'URUCARÁ');
Insert Into Cidade (Nome, Estado) Values ('TO', 'ARAGUATINS');
Insert Into Cidade (Nome, Estado) Values ('MT', 'CONFRESA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'COTRIGUAÇU');
Insert Into Cidade (Nome, Estado) Values ('RR', 'PACAIMA');
Insert Into Cidade (Nome, Estado) Values ('RR', 'CARACARAÍ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'COCALINHO');
Insert Into Cidade (Nome, Estado) Values ('PA', 'TERRA SANTA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'ARAGARÇAS');
Insert Into Cidade (Nome, Estado) Values ('PE', 'ARARIPINA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'ADUSTINA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'JANAÚBA');
Insert Into Cidade (Nome, Estado) Values ('CE', 'ARACATI');
Insert Into Cidade (Nome, Estado) Values ('BA', 'JUAZEIRO');
Insert Into Cidade (Nome, Estado) Values ('MA', 'BACABAL');
Insert Into Cidade (Nome, Estado) Values ('BA', 'BARREIRAS');
Insert Into Cidade (Nome, Estado) Values ('MA', 'BALSAS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'BRUMADO');
Insert Into Cidade (Nome, Estado) Values ('PA', 'IPIXUNA DO PARÁ');
Insert Into Cidade (Nome, Estado) Values ('PA', 'BAIÃO');
Insert Into Cidade (Nome, Estado) Values ('BA', 'BARRA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'CAPANEMA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'RURÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'REDENÇÃO');
Insert Into Cidade (Nome, Estado) Values ('MA', 'TIMON');
Insert Into Cidade (Nome, Estado) Values ('MG', 'DIAMANTINA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'DIVINÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'PARAGOMINAS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'ALFENAS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SÃO FÉLIX DO XINGU');
Insert Into Cidade (Nome, Estado) Values ('BA', 'GUANAMBI');
Insert Into Cidade (Nome, Estado) Values ('PE', 'SERRA TALHADA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'IRECÊ');
Insert Into Cidade (Nome, Estado) Values ('CE', 'IGUATU');
Insert Into Cidade (Nome, Estado) Values ('BA', 'IPIAÚ');
Insert Into Cidade (Nome, Estado) Values ('BA', 'JACOBINA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'FEIRA DE SANTANA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'JEQUIÉ');
Insert Into Cidade (Nome, Estado) Values ('MG', 'SÃO JOÃO DEL REI');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SANTANA DO ARAGUAIA');
Insert Into Cidade (Nome, Estado) Values ('ES', 'CACHOEIRO DE ITAPEMIRIM');
Insert Into Cidade (Nome, Estado) Values ('RN', 'CAICÓ');
Insert Into Cidade (Nome, Estado) Values ('PA', 'MONTE ALEGRE');
Insert Into Cidade (Nome, Estado) Values ('GO', 'PIRENÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'MARACÁS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'JAÍBA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'MUCURI');
Insert Into Cidade (Nome, Estado) Values ('ES', 'SÃO MATEUS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'PORTO DE MOZ');
Insert Into Cidade (Nome, Estado) Values ('CE', 'SOBRAL');
Insert Into Cidade (Nome, Estado) Values ('PI', 'PICOS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'PATOS DE MINAS');
Insert Into Cidade (Nome, Estado) Values ('AP', 'PORTO GRANDE');
Insert Into Cidade (Nome, Estado) Values ('MG', 'PATROCÍNIO');
Insert Into Cidade (Nome, Estado) Values ('BA', 'MORRO DE SÃO PAULO');
Insert Into Cidade (Nome, Estado) Values ('PA', 'BARCARENA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'SÃO SEBASTIÃO DO PARAÍSO');
Insert Into Cidade (Nome, Estado) Values ('PB', 'SOUSA');
Insert Into Cidade (Nome, Estado) Values ('PI', 'FLORIANO');
Insert Into Cidade (Nome, Estado) Values ('PE', 'CARUARU');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SALINÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SOURE');
Insert Into Cidade (Nome, Estado) Values ('BA', 'TEIXEIRA DE FREITAS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'TEÓFILO OTONI');
Insert Into Cidade (Nome, Estado) Values ('PA', 'TAILÂNDIA');
Insert Into Cidade (Nome, Estado) Values ('PB', 'PATOS');
Insert Into Cidade (Nome, Estado) Values ('MG', 'UBÁ');
Insert Into Cidade (Nome, Estado) Values ('RN', 'AÇU');
Insert Into Cidade (Nome, Estado) Values ('MG', 'ARAÇUAÍ');
Insert Into Cidade (Nome, Estado) Values ('PA', 'ULIANÓPOLIS');
Insert Into Cidade (Nome, Estado) Values ('BA', 'VALENÇA');
Insert Into Cidade (Nome, Estado) Values ('BA', 'VERA CRUZ');
Insert Into Cidade (Nome, Estado) Values ('PA', 'BREVES');
Insert Into Cidade (Nome, Estado) Values ('BA', 'VALENTE');
Insert Into Cidade (Nome, Estado) Values ('PA', 'SENADOR JOSÉ PORFÍRIO');
Insert Into Cidade (Nome, Estado) Values ('MT', 'QUERÊNCIA');
Insert Into Cidade (Nome, Estado) Values ('MG', 'ITUIUTABA');
Insert Into Cidade (Nome, Estado) Values ('PA', 'MOJU');
Insert Into Cidade (Nome, Estado) Values ('MG', 'POUSO ALEGRE');
Insert Into Cidade (Nome, Estado) Values ('MS', 'BODOQUENA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'BENTO GONÇALVES');
Insert Into Cidade (Nome, Estado) Values ('SC', 'CONCÓRDIA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'CANELA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'ERECHIM');
Insert Into Cidade (Nome, Estado) Values ('PR', 'FRANCISCO BELTRÃO');
Insert Into Cidade (Nome, Estado) Values ('RS', 'HORIZONTINA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'IJUÍ');
Insert Into Cidade (Nome, Estado) Values ('SC', 'JOAÇABA');
Insert Into Cidade (Nome, Estado) Values ('PR', 'CAMPO MOURÃO');
Insert Into Cidade (Nome, Estado) Values ('RO', 'CACOAL');
Insert Into Cidade (Nome, Estado) Values ('PR', 'LARANJEIRAS DO SUL');
Insert Into Cidade (Nome, Estado) Values ('RS', 'ALEGRETE');
Insert Into Cidade (Nome, Estado) Values ('GO', 'APORÉ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'SÃO FÉLIX DO ARAGUAIA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'NOVO HAMBURGO');
Insert Into Cidade (Nome, Estado) Values ('MT', 'GUARANTÃ DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('SC', 'SÃO MIGUEL DO OESTE');
Insert Into Cidade (Nome, Estado) Values ('PR', 'PATO BRANCO');
Insert Into Cidade (Nome, Estado) Values ('PR', 'PARANAGUÁ');
Insert Into Cidade (Nome, Estado) Values ('PR', 'PORECATU');
Insert Into Cidade (Nome, Estado) Values ('RS', 'SANTA CRUZ DO SUL');
Insert Into Cidade (Nome, Estado) Values ('PR', 'UMUARAMA');
Insert Into Cidade (Nome, Estado) Values ('SC', 'VIDEIRA');
Insert Into Cidade (Nome, Estado) Values ('RS', 'SANTA ROSA');
Insert Into Cidade (Nome, Estado) Values ('RR', 'ALTO ALEGRE');
Insert Into Cidade (Nome, Estado) Values ('AM', 'BARCELOS');
Insert Into Cidade (Nome, Estado) Values ('AM', 'BARREIRINHA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'BORBA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'PEIXOTO DE AZEVEDO');
Insert Into Cidade (Nome, Estado) Values ('RR', 'AMAJARI');
Insert Into Cidade (Nome, Estado) Values ('AM', 'CARAUARI');
Insert Into Cidade (Nome, Estado) Values ('GO', 'CAMPOS BELOS');
Insert Into Cidade (Nome, Estado) Values ('MT', 'ARIPUANÃ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'CAMPO NOVO DO PARECIS');
Insert Into Cidade (Nome, Estado) Values ('RO', 'COSTA MARQUES');
Insert Into Cidade (Nome, Estado) Values ('GO', 'SÃO MIGUEL DO ARAGUAIA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'DIAMANTINO');
Insert Into Cidade (Nome, Estado) Values ('AM', 'ATALAIA DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('AM', 'EIRUNEPÉ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'CANARANA');
Insert Into Cidade (Nome, Estado) Values ('AC', 'FEIJÓ');
Insert Into Cidade (Nome, Estado) Values ('TO', 'GURUPI');
Insert Into Cidade (Nome, Estado) Values ('TO', 'ARAGUAÍNA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'PALMEIRAS DE GOIÁS');
Insert Into Cidade (Nome, Estado) Values ('GO', 'SANTA HELENA DO GOIÁS');
Insert Into Cidade (Nome, Estado) Values ('MT', 'ÁGUA BOA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'HUMAITÁ');
Insert Into Cidade (Nome, Estado) Values ('AM', 'SANTO ANTÔNIO DO IÇÁ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'JUÍNA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'JAPURÁ');
Insert Into Cidade (Nome, Estado) Values ('MS', 'SELVÍRIA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'JURUENA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'JATAÍ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'CÁCERES');
Insert Into Cidade (Nome, Estado) Values ('AM', 'LÁBREA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'RIO VERDE');
Insert Into Cidade (Nome, Estado) Values ('MT', 'SANTO ANTÔNIO DO LEVERGER');
Insert Into Cidade (Nome, Estado) Values ('AM', 'MAUÉS');
Insert Into Cidade (Nome, Estado) Values ('AM', 'NOVO ARIPUANÃ');
Insert Into Cidade (Nome, Estado) Values ('GO', 'ARUANÃ');
Insert Into Cidade (Nome, Estado) Values ('AM', 'BOCA DO ACRE');
Insert Into Cidade (Nome, Estado) Values ('AM', 'NOVA OLINDA DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('GO', 'NIQUELÂNDIA');
Insert Into Cidade (Nome, Estado) Values ('AM', 'FONTE BOA');
Insert Into Cidade (Nome, Estado) Values ('RR', 'BONFIM');
Insert Into Cidade (Nome, Estado) Values ('AM', 'PRESIDENTE FIGUEIREDO');
Insert Into Cidade (Nome, Estado) Values ('AM', 'PARINTINS');
Insert Into Cidade (Nome, Estado) Values ('MT', 'PORTO ALEGRE DO NORTE');
Insert Into Cidade (Nome, Estado) Values ('MT', 'SINOP');
Insert Into Cidade (Nome, Estado) Values ('AM', 'SANTA ISABEL DO RIO NEGRO');
Insert Into Cidade (Nome, Estado) Values ('MT', 'TANGARÁ DA SERRA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'VILA RICA');
Insert Into Cidade (Nome, Estado) Values ('GO', 'PORANGATU');
Insert Into Cidade (Nome, Estado) Values ('GO', 'URUAÇU');
Insert Into Cidade (Nome, Estado) Values ('MT', 'MATUPÁ');
Insert Into Cidade (Nome, Estado) Values ('MT', 'NOVA XAVANTINA');
Insert Into Cidade (Nome, Estado) Values ('MT', 'POCONÉ');
Insert Into Cidade (Nome, Estado) Values ('AM', 'APUÍ');
Insert Into Cidade (Nome, Estado) Values ('GO', 'USINA SÃO SIMÃO');
